### ISSUE TITLE
Is it currently using by lichess website?

### ISSUE THREAD

**Issue by B-Esmaili** [clarkerubber/irwin#14]
Hi and thanks for this great piece of code. you've  mentioned  

> the protector of lichess from all chess players villainous

 Is it really in use by this website?and if yes is this code fully functional copy of same thing `lichess` is using?

**Comment by ornicar** [comment]
yes

**Comment by B-Esmaili** [comment]
you are so great men.is there any docs on how to use this library?

**Comment by ornicar** [comment]
no

**Comment by cclx-tools** [comment]
You may wanna close that issue?

**Comment by ComputeShader** [comment]
You may wanna close that issue?
