### ISSUE TITLE
Support password protected MongoDB

### ISSUE THREAD

**Issue by niklasf** [clarkerubber/irwin#17]
If it's reasonably easy to add. For low priority hardening (see internal https://github.com/lichess-org/sysadmin/issues/58#issuecomment-700695801).

**Comment by jirislav** [comment]
Hi, I'm considering to work on this issue, as it seems like a good issue to start, but I can't see the link contents as I'm not member of the group. Could you please share the motivation here for us, newcomers?

**Comment by niklasf** [comment]
The irwin service runs on a server that has no private shared network with the rest of the infrastructure. So the only thing protecting its MongoDB from the open internet is firewall rules, which is a bit fragile.

**Comment by jirislav** [comment]
Well, that's surprising, because the README says, that `irwin` supports DB authentication configuration, see https://github.com/clarkerubber/irwin#create-confconfigjson

---

## Configuring
### Create `conf/config.json`
```json
{
  "api": {
    "url": "https://lichess.org/",
    "token": "token"
  },
  "stockfish": {
    "threads": 4,
    "memory": 2048,
    "nodes": 4500000,
    "update": false
  },
  "db": {
    "host": "localhost",
    "port": 27017,
    "authenticate": false,
    "authentication": {
      "username": "username",
      "password": "password"
    }
  },
  "irwin": {
    "train": {
      "batchSize": 5000,
      "cycles": 80
    }
  }
}
```

`conf/config.json` contains config for stockfish, mongodb, tensorflow, lichess (authentication token and URL), etc...

**Comment by niklasf** [comment]
Oh, so it was supported all along! Sorry for wasting your time.

**Comment by jirislav** [comment]
> Oh, so it was supported all along! Sorry for wasting your time.

Don't worry, it wasn't wasted ;)
