### ISSUE TITLE
Input LeelaZero evaluations

### ISSUE THREAD

**Issue by ddugovic** [clarkerubber/irwin#7]
ML-based engines are the next big thing, with a focus on NN.  Adding input to Irwin's model can only increase its accuracy:
~https://github.com/glinscott/leela-chess~

**Comment by careless25** [comment]
correcting the link as the repo has moved: https://github.com/LeelaChessZero/lczero

**Comment by ddugovic** [comment]
Now that SF-NNUE is a thing, I no longer see a need for my request.
